### ISSUE TITLE
Please replaced some symbol place

### ISSUE THREAD

**Issue by iBabu007** [rajput-hemant/calculator#59]
See this image
Merged delete & Clear together single press for delete and long press for clear.

![Screenshot_20220718-231015_1](https://user-images.githubusercontent.com/65340361/179571952-9f159e74-4cc2-4f35-9e4a-5b77dde1a10b.png)

**Comment by rajput-hemant** [comment]
@iBabu007 Thanks for sharing your suggestion about merging the delete and clear functions. I understand your point, but I've decided to keep them separate for now to maintain a simple and intuitive user experience. I really appreciate your feedback, and if you have any more ideas or suggestions, please don't hesitate to let me know. Thanks for your support!
