### ISSUE TITLE
some bugs I've encountered 

### ISSUE THREAD

**Issue by Sikeen** [rajput-hemant/calculator#63]
I've found two bugs:
1: When a conversion gets too big it blocks for the menu. I would suggest a buffer a few milimeter from the menu, and after the conversion gets too many numbers on, it could go to the next line

2: the conversions arent sorted after size fx: terabyte could be before gigabyte

**Comment by rajput-hemant** [comment]
Please check out the new release as the issue has been resolved in the v0.2.0.
