### ISSUE TITLE
App keeps closing when opened

### ISSUE THREAD

**Issue by niccokunzmann** [rajput-hemant/calculator#85]
I am using the version 0.2.3  from F-Droid. When I open the app, it just closes and I do not know why.
Samsung Galaxy A12, no Internet connection.

**Comment by rajput-hemant** [comment]
Please download the most recent release APK from this link: [Calculator v0.2.4](https://github.com/rajput-hemant/calculator/releases/tag/v0.2.4). The issue you mentioned has been resolved in [this commit](https://github.com/rajput-hemant/calculator/commit/17454fb181ed205ca29c77885e5209008ae29eac).

Additionally, I would greatly appreciate it if you could provide me with the F-Droid repository link for my APK, as I am currently unable to locate it.

**Comment by niccokunzmann** [comment]
Thanks!

Calculator (simple Material Calculator and Unit Converter)
https://f-droid.org/packages/com.capybara.calculator/

I would probably only use the f-droid apk. A tag will likely cause a new build.
