### ISSUE TITLE
Click problem

### ISSUE THREAD

**Issue by Shivamhobbyist** [rajput-hemant/calculator#87]
Sometime button doesn't works when press c button then work properly

**Comment by rajput-hemant** [comment]
@Shivamhobbyist Thanks for reporting the button issue. To help me address it, could you please specify which button(s) are causing problems and on which screen this occurs? Any additional details would be greatly appreciated.

**Comment by Shivamhobbyist** [comment]
Maybe we can't share screen recording here you can watch by link
https://drive.google.com/file/d/1O_zglBy5-StsXiJ626zIVhUSnqnhdiWe/view?usp=drivesdk
Samsung galaxy a34 5g Android 13 One UI 5.1

**Comment by rajput-hemant** [comment]
@Shivamhobbyist 
The Drive link is currently set to private. Could you please either make it public or should I send an access request?

**Comment by Shivamhobbyist** [comment]
> @Shivamhobbyist 
> The Drive link is currently set to private. Could you please either make it public or should I send an access request?

Watch again

**Comment by Shivamhobbyist** [comment]
> @Shivamhobbyist 
> This is a known issue. Please refer to #73 for updates. I will notify you as soon as this issue is resolved. For now, I am closing this issue in favor of #73.

Okay
