### ISSUE TITLE
Temperature conversion is actually Area conversion?

### ISSUE THREAD

**Issue by Ao1Pointblank** [rajput-hemant/calculator#99]
As you can see from the screenshot, the header for temperature conversion actually says Area, and the numbers of course are not reflecting temperature scales. It made me laugh, I thought this might be a copy-paste code error?
![Screenshot_20231116-094249](https://github.com/rajput-hemant/calculator/assets/88149675/57ed0236-6f03-49e9-9642-dc1541e6e2b2)

**Comment by rajput-hemant** [comment]
@Ao1Pointblank Yes, that's indeed a copy-paste error, hehe. I apologize for the confusion. I'll rectify it shortly and will make sure to update you once the latest builds are ready.
